'use client';

import { useEffect, useMemo, useState } from 'react';
import { apiGet, API_BASE_URL } from './api';
import type { HistoryResponse, IndicatorsResponse, MarketIndex, Quote } from './types';
import StockChart from './StockChart';
import StockSearch from './StockSearch';
import { fetchStooqDailyHistory, mapTickerToStooqSymbol } from './publicApis';

const DEFAULT_TICKERS = ['TW:2330', 'US:AAPL'];

export default function DashboardClient() {
  const [twIndex, setTwIndex] = useState<MarketIndex | null>(null);
  const [usIndices, setUsIndices] = useState<MarketIndex[]>([]);

  const [ticker, setTicker] = useState<string>(DEFAULT_TICKERS[1]);
  const [quote, setQuote] = useState<Quote | null>(null);
  const [history, setHistory] = useState<HistoryResponse | null>(null);
  const [ind, setInd] = useState<IndicatorsResponse | null>(null);

  const [error, setError] = useState<string | null>(null);
  const [stockMsg, setStockMsg] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const candleCount = history?.candles?.length ?? 0;

  const normalizedTicker = useMemo(() => {
    const raw = ticker.trim().toUpperCase();
    if (!raw) return raw;
    if (raw.includes(':')) return raw;
    // Shorthand support:
    // - "2330" => TW:2330
    // - "AAPL" => US:AAPL
    if (/^\d{3,6}$/.test(raw)) return `TW:${raw}`;
    if (/^[A-Z.]{1,10}$/.test(raw)) return `US:${raw}`;
    return raw;
  }, [ticker]);

  // Debug: log what's happening
  const [debugLog, setDebugLog] = useState<string[]>([]);

  useEffect(() => {
    (async () => {
      const logs: string[] = [];

      // If backend is configured, use it; otherwise fall back to public no-key APIs.
      if (API_BASE_URL) {
        logs.push('Backend mode: ' + API_BASE_URL);
        try {
          setError(null);
          const tw = await apiGet<MarketIndex>('/api/market/tw/index');
          setTwIndex(tw);
          logs.push('TW index loaded');
        } catch (e: any) {
          logs.push('TW error: ' + (e?.message || String(e)));
          setError(e?.message || String(e));
        }

        try {
          const us = await apiGet<{ items: MarketIndex[] }>('/api/market/us/indices');
          setUsIndices(us.items || []);
          logs.push('US indices loaded: ' + us.items?.length);
        } catch (e: any) {
          logs.push('US error: ' + (e?.message || String(e)));
        }
        setDebugLog(logs);
        return;
      }

      // Static JSON (generated by GitHub Actions) — avoids browser CORS issues.
      logs.push('Static JSON mode');
      try {
        setError(null);
        const res = await fetch('./data/taiex.json', { cache: 'no-store' });
        logs.push('taiex.json fetch status: ' + res.status);
        if (!res.ok) throw new Error(`taiex.json ${res.status}`);
        const tw: any = await res.json();
        setTwIndex(tw);
        logs.push('TAIEX loaded: ' + tw.price);
      } catch (e: any) {
        const msg = e?.message || String(e);
        logs.push('TAIEX error: ' + msg);
        setError(msg);
      }

      try {
        const res = await fetch('./data/us-indices.json', { cache: 'no-store' });
        logs.push('us-indices.json fetch status: ' + res.status);
        if (!res.ok) throw new Error(`us-indices.json ${res.status}`);
        const us: any = await res.json();
        setUsIndices(us.items || []);
        logs.push('US indices loaded: ' + us.items?.length);
      } catch (e: any) {
        const msg = e?.message || String(e);
        logs.push('US error: ' + msg);
      }

      setDebugLog(logs);
    })();
  }, []);

  async function loadTicker(t: string) {
    setLoading(true);
    setStockMsg(null);
    // keep global error for index section only

    // Backend mode
    if (API_BASE_URL) {
      try {
        const q = await apiGet<Quote>(`/api/stock/${encodeURIComponent(t)}/quote`);
        setQuote(q);
      } catch (e: any) {
        setQuote(null);
        setError(e?.message || String(e));
      }

      try {
        const h = await apiGet<HistoryResponse>(
          `/api/stock/${encodeURIComponent(t)}/history?interval=1d&period=1y`
        );
        setHistory(h);
      } catch (e: any) {
        setHistory(null);
        setError((prev) => prev || (e?.message || String(e)));
      }

      try {
        const r = await apiGet<IndicatorsResponse>(
          `/api/stock/${encodeURIComponent(t)}/indicators?interval=1d&period=1y&types=ma,rsi,macd`
        );
        setInd(r);
      } catch {
        setInd(null);
      }

      setLoading(false);
      return;
    }

    // GitHub Pages demo mode (no backend): use public APIs (stooq) best-effort
    try {
      const stooq = mapTickerToStooqSymbol(t);
      const candles = await fetchStooqDailyHistory(stooq);
      setHistory({ ticker: t, interval: '1d', candles });

      const last = candles[candles.length - 1];
      if (last) {
        setQuote({
          ticker: t,
          ts: last.time,
          price: last.close,
          currency: t.toUpperCase().startsWith('TW:') ? 'TWD' : 'USD',
          source: 'stooq',
          is_delayed: true,
          open: last.open,
          high: last.high,
          low: last.low,
          volume: last.volume ?? null
        });
      } else {
        setQuote(null);
      }

      // Keep indicators empty in demo mode for now
      setInd(null);
    } catch (e: any) {
      setQuote(null);
      setHistory(null);
      setInd(null);
      setStockMsg(`Demo 模式抓不到 ${t}（stooq）。你可以先試 US:AAPL；要完整支援請部署後端。`);
    }

    setLoading(false);
  }

  useEffect(() => {
    // In GitHub Pages demo mode (no backend), avoid auto-loading stock to prevent scary red errors.
    // User can click quick switch / load manually.
    if (API_BASE_URL) {
      loadTicker(normalizedTicker);
    } else {
      setStockMsg('Demo 模式：個股資料需部署後端才會完整（你仍可嘗試載入 US:AAPL）。');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="grid" style={{ gap: 16 }}>
      <div className="grid grid-3">
        <div className="card">
          <div className="small">台股指數</div>
          <div style={{ fontSize: 20, fontWeight: 700 }}>
            {twIndex ? Number(twIndex.price).toLocaleString() : '—'}
          </div>
          <div className="small mono">
            {twIndex ? `${twIndex.source} · delayed=${twIndex.is_delayed} · ${new Date(twIndex.ts).toLocaleString()}` : ''}
          </div>
          {twIndex && (
            <details style={{ marginTop: 8 }}>
              <summary className="small">raw</summary>
              <div className="mono small" style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(twIndex, null, 2)}</div>
            </details>
          )}
        </div>
        <div className="card">
          <div className="small">美股指數</div>
          {usIndices.length ? (
            <div style={{ marginTop: 6 }}>
              {usIndices.map((x) => (
                <div key={x.code} className="row" style={{ justifyContent: 'space-between' }}>
                  <div className="small">{x.name}</div>
                  <div className="mono small">{Number(x.price).toLocaleString(undefined, { maximumFractionDigits: 2 })}</div>
                </div>
              ))}
              <div className="small mono" style={{ marginTop: 6 }}>
                {`${usIndices[0]?.source ?? 'source'} · delayed=true · ${new Date(usIndices[0]?.ts ?? Date.now()).toLocaleString()}`}
              </div>
              <details style={{ marginTop: 8 }}>
                <summary className="small">raw</summary>
                <div className="mono small" style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(usIndices, null, 2)}</div>
              </details>
            </div>
          ) : (
            <div className="small" style={{ marginTop: 6, opacity: 0.85 }}>—</div>
          )}
        </div>
        <div className="card">
          <div className="small">快速切換</div>
          <div className="row" style={{ marginTop: 8 }}>
            {DEFAULT_TICKERS.map((t) => (
              <button
                key={t}
                className="btn"
                onClick={() => {
                  setTicker(t);
                  loadTicker(t);
                }}
              >
                {t}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="card">
        <div className="row" style={{ justifyContent: 'space-between' }}>
          <div>
            <div style={{ fontWeight: 700 }}>個股</div>
            <div className="small">輸入 ticker：例如 TW:2330 / US:AAPL</div>
          </div>
          <div className="small mono">candles={candleCount}</div>
        </div>

        <div className="row" style={{ marginTop: 12 }}>
          <input
            className="input mono"
            value={ticker}
            onChange={(e) => setTicker(e.target.value)}
            placeholder="可輸入：2330 / TW:2330 / AAPL / US:AAPL"
          />
          <button
            className="btn"
            onClick={() => {
              setTicker(normalizedTicker);
              loadTicker(normalizedTicker);
            }}
            disabled={loading}
          >
            {loading ? '載入中' : '載入'}
          </button>
        </div>

        {stockMsg && (
          <div className="card" style={{ marginTop: 12, borderColor: 'rgba(251,191,36,0.35)' }}>
            <div style={{ fontWeight: 700 }}>提示</div>
            <div className="small mono" style={{ whiteSpace: 'pre-wrap' }}>{stockMsg}</div>
          </div>
        )}

        {error && (
          <div className="card" style={{ marginTop: 12, borderColor: 'rgba(220,38,38,0.5)' }}>
            <div style={{ fontWeight: 700 }}>錯誤</div>
            <div className="small mono" style={{ whiteSpace: 'pre-wrap' }}>{error}</div>
          </div>
        )}

        <div className="grid" style={{ gridTemplateColumns: '1fr 1fr', marginTop: 12 }}>
          <div className="card">
            <div className="small">Quote</div>
            {quote ? (
              <div style={{ marginTop: 8 }}>
                <div className="row" style={{ justifyContent: 'space-between' }}>
                  <div className="small">Ticker</div>
                  <div className="mono small">{quote.ticker}</div>
                </div>
                <div className="row" style={{ justifyContent: 'space-between' }}>
                  <div className="small">Price</div>
                  <div className="mono small">{Number(quote.price).toLocaleString(undefined, { maximumFractionDigits: 4 })} {quote.currency}</div>
                </div>
                <div className="row" style={{ justifyContent: 'space-between' }}>
                  <div className="small">O/H/L</div>
                  <div className="mono small">
                    {quote.open ?? '—'} / {quote.high ?? '—'} / {quote.low ?? '—'}
                  </div>
                </div>
                <div className="row" style={{ justifyContent: 'space-between' }}>
                  <div className="small">Volume</div>
                  <div className="mono small">{quote.volume ? Number(quote.volume).toLocaleString() : '—'}</div>
                </div>
                <div className="row" style={{ justifyContent: 'space-between' }}>
                  <div className="small">Source</div>
                  <div className="mono small">{quote.source} · delayed={String(quote.is_delayed)}</div>
                </div>
                <div className="row" style={{ justifyContent: 'space-between' }}>
                  <div className="small">TS</div>
                  <div className="mono small">{new Date(quote.ts).toLocaleString()}</div>
                </div>

                <details style={{ marginTop: 8 }}>
                  <summary className="small">raw</summary>
                  <div className="mono small" style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(quote, null, 2)}</div>
                </details>
              </div>
            ) : (
              <div className="small" style={{ marginTop: 8, opacity: 0.85 }}>—</div>
            )}
          </div>
          <div className="card">
            <div className="small">Indicators</div>
            <div className="mono small" style={{ whiteSpace: 'pre-wrap' }}>{ind ? JSON.stringify(ind.indicators, null, 2) : '—'}</div>
          </div>
        </div>

        <div className="card" style={{ marginTop: 12 }}>
          <div className="small">K 線</div>
          {history?.candles?.length ? <StockChart candles={history.candles} /> : <div className="small">—</div>}
        </div>
      </div>

      <div className="card">
        <div style={{ fontWeight: 700, marginBottom: 8 }}>搜尋（中文/英文/股號）</div>
        <div className="small" style={{ marginBottom: 10, opacity: 0.85 }}>
          直接打：台積 / 2330 / TSMC / AAPL / Apple… 點一下就會載入。
        </div>
        {/* search UI */}
        <StockSearch onPick={(t) => { setTicker(t); loadTicker(t); }} />
      </div>

      {/* Debug info */}
      {debugLog.length > 0 && (
        <div className="card" style={{ borderColor: 'rgba(255,255,0,0.3)' }}>
          <div className="small" style={{ color: '#fbbf24' }}>Debug:</div>
          {debugLog.map((log, i) => (
            <div key={i} className="mono small" style={{ whiteSpace: 'pre-wrap' }}>{log}</div>
          ))}
        </div>
      )}
    </div>
  );
}
